# Generated by Django 5.2.1 on 2025-05-26 14:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
        ('Productos', '0002_alter_producto_descripcion_alter_categoria_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField(auto_now_add=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente')),
            ],
            options={
                'db_table': 'Venta',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle_venta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('subTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ManyToManyField(to='Productos.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Ventas.ventas')),
            ],
            options={
                'db_table': 'DetalleVenta',
            },
        ),
    ]
